# Generated by Django 4.2.7 on 2023-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
