# Generated by Django 4.1.3 on 2023-09-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdei', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='name',
        ),
    ]
